spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
    url: jdbc:h2:~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
#        type: trace # p6spy 로 대체